### PR TITLE
some fixes on service bus and sql db

### PR DESCRIPTION
**Pull request by zhongyi-zhang**
**service bus:**
Fix error callback.

Use uniform http status code and message.

**sql db:**
Fix resource group location parameter getting issue.

Fix error callback issue on creating SQL server.

@sebastus 
Could you review the part of sql db? All the changes are in the commit https://github.com/Azure/meta-azure-service-broker/pull/15/commits/94faf41ae22a54777b0ec658e89fa031a77f6781 . Thanks.

### CODE REVIEW

**Comment by sebastus** [comment]
re: adding location to reqParams.  
The problem with this approach is that the location isn't the location of the resource group, but the location of the sql server.  A sql server can be created in a region different from the region of the resource group.  This change is incorrect.

re: adding check for HttpStatus.CREATED.
Have you actually observed this outcome?  I have never seen it in all of my testing.  If it's occurring, then the changes needed are much greater than simply returning an error.

**Comment by zhongyi-zhang** [comment]
@sebastus 
re:re: adding location to reqParams.
I used the example configuration in sql db document, then I got this:
500 Internal Server Error, Body: {"code":"InternalError","message":"Cannot read property 'location' of undefined"}
I think it was caused by the requirement of location to create resource group and the absence of default value for location. In other hand, the doc doesn't mention where to set the location for resource group. 

re:re: adding check for HttpStatus.CREATED.
Through my test, error 409 caused by creating a sql server with the same name to another sql server in a different resource group didn't callback as an error. So, we need to read the status code to distinguish errors.

**Comment by sebastus** [comment]
Looked more closely:

re: resource group location.  I agree with your solution.

re: sql server already exists in another resource group.  
When you create a new sql server correctly, it's not returning a CREATED.  It's returning an OK.  I don't know why the docs say it'll return CREATED - maybe it used to take a lot longer.  Anyway - I think if you change the test to look for OK, the fix will be correct.

Thanks for your help with this, zhongyi-zhang!  :)

**Comment by bingosummer** [comment]
Thanks @sebastus for your kindly review.
LGTM, merging it.

**Comment by sebastus** [comment]
@bingosummer did you change the check for CREATED to OK?

**Comment by zhongyi-zhang** [comment]
@sebastus 
Thanks for your reminding!
I tested the response status code again.

Added this line to https://github.com/Azure/meta-azure-service-broker/blob/master/lib/services/azuresqldb/client.js#L230 :
    that.log.info('CREATING SQL SERVER STATUSCODE:', res.statusCode);
And Created a sqldb service instance.

Then I got this from log:
    2016-08-05T02:55:31.84+0000 [App/0]      OUT 2:55:31 AM - INFO  - Meta Azure Service Broker - CREATING SQL SERVER STATUSCODE: 201

I think the docs is right. :)

**Pull request merged**
