### PR TITLE
add 'configurable: true' to sql server pool collection blueprints'

### PR DESCRIPTION
**Pull request by erniebilling**
Fix for missing 'configurable: true' blueprints for sql server pools

### CODE REVIEW

**Comment by jastev** [comment]
@mattdot to review

**Comment by zhongyi-zhang** [comment]
Any update on the tile generator side? If I remember correctly, a field is also configurable without the property `configurable: true`. Anyway, the change LGTM.

**Comment by jseely** [comment]
@zhongyi-zhang you are correct that that was the experience in the past due to a bug in OpsManager. That bug has been patched and now requires explicit `configurable: true`.

@mattdot any word on getting this merged?

**Comment by jseely** [comment]
@thomas1206 can you help here?

**Pull request merged**
