### PR TITLE
add example json files for all the brokers and fix some bugs

### LINKED ISSUE #3: Add retry for broker db operation
meta-azure-service-broker currently use azure sql as database to log status of provision,deprovision, etc. of a service. Sometimes it fails to connect to azure sql or fails to insert/rm/update a record, and thus lead the failures of subsequent operations. In this case, a retry is needed.

### PR DESCRIPTION
**Pull request by zhongyi-zhang**
1. Add example json with parameters description for all the brokers.

2. Add retry for sql database operations. Fix #3.

3. Remove default parameters in storage blob service and service bus service.

4. Fix errors callback and add callback function to throw them out.

5. Update unit tests and integration tests for new changes.

### CODE REVIEW

**Comment by bingosummer** [comment]
@zhongyi-zhang There are two commits about security issues. Can you rebase them into a single one?

**Comment by bingosummer** [comment]
@sebastus Do you have any comment on this PR? Thanks in advance.

**Comment by sebastus** [comment]
I looked through the code review and only saw one thing that concerned me - the removal of the version from the redis parameters.  I assume you tested though.  Everything looked fine otherwise.

**Comment by zhongyi-zhang** [comment]
@sebastus 
Yes, I've tested it and it run well.
And according to [this document](http://azure.github.io/azure-sdk-for-node/azure-arm-rediscache/latest/Redis.html#createOrUpdate),  redis version is no longer necessary to provide and any value specified is ignored.

**Comment by zhongyi-zhang** [comment]
@bingosummer 
Rebase done.

**Pull request merged**
